let project = {
  Project: {
    $: {
      xmlns: "http://schemas.microsoft.com/project",
    },
    SaveVersion: ["14"],
    BuildNumber: ["16.0.17830.20138"],
    Name: ["test project_1_foo.xml"],
    GUID: ["8440CED1-84E2-E111-9B71-001AA0D20198"],
    Title: ["Simple Project Plan"],
    Author: ["Heather O'Cull"],
    CreationDate: ["2024-08-07T15:12:00"],
    LastSaved: ["2024-08-12T23:34:00"],
    ScheduleFromStart: ["1"],
    StartDate: ["2024-08-07T08:00:00"],
    FinishDate: ["2024-08-29T17:00:00"],
    FYStartDate: ["1"],
    CriticalSlackLimit: ["0"],
    CurrencyDigits: ["2"],
    CurrencySymbol: ["$"],
    CurrencyCode: ["USD"],
    CurrencySymbolPosition: ["0"],
    CalendarUID: ["1"],
    DefaultStartTime: ["08:00:00"],
    DefaultFinishTime: ["17:00:00"],
    MinutesPerDay: ["480"],
    MinutesPerWeek: ["2400"],
    DaysPerMonth: ["20"],
    DefaultTaskType: ["0"],
    DefaultFixedCostAccrual: ["3"],
    DefaultStandardRate: ["0"],
    DefaultOvertimeRate: ["0"],
    DurationFormat: ["7"],
    WorkFormat: ["2"],
    EditableActualCosts: ["0"],
    HonorConstraints: ["0"],
    InsertedProjectsLikeSummary: ["1"],
    MultipleCriticalPaths: ["0"],
    NewTasksEffortDriven: ["0"],
    NewTasksEstimated: ["1"],
    SplitsInProgressTasks: ["1"],
    SpreadActualCost: ["0"],
    SpreadPercentComplete: ["0"],
    TaskUpdatesResource: ["1"],
    FiscalYearStart: ["0"],
    WeekStartDay: ["0"],
    MoveCompletedEndsBack: ["0"],
    MoveRemainingStartsBack: ["0"],
    MoveRemainingStartsForward: ["0"],
    MoveCompletedEndsForward: ["0"],
    BaselineForEarnedValue: ["0"],
    AutoAddNewResourcesAndTasks: ["1"],
    CurrentDate: ["2024-08-12T08:00:00"],
    MicrosoftProjectServerURL: ["1"],
    Autolink: ["0"],
    NewTaskStartDate: ["0"],
    NewTasksAreManual: ["1"],
    DefaultTaskEVMethod: ["0"],
    ProjectExternallyEdited: ["0"],
    ExtendedCreationDate: ["1984-01-01T00:00:00"],
    ActualsInSync: ["0"],
    RemoveFileProperties: ["0"],
    AdminProject: ["0"],
    UpdateManuallyScheduledTasksWhenEditingLinks: ["1"],
    KeepTaskOnNearestWorkingTimeWhenMadeAutoScheduled: ["0"],
    Views: [
      {
        View: [
          {
            Name: ["Gantt &with Timeline"],
            IsCustomized: ["true"],
          },
          {
            Name: ["&Gantt Chart"],
            IsCustomized: ["true"],
          },
          {
            Name: ["Time&line"],
            IsCustomized: ["true"],
          },
          {
            Name: ["Resource &Sheet"],
            IsCustomized: ["true"],
          },
        ],
      },
    ],
    Filters: [
      {
        Filter: [
          {
            Name: ["&All Tasks"],
          },
          {
            Name: ["&All Resources"],
          },
        ],
      },
    ],
    Groups: [
      {
        Group: [
          {
            Name: ["&No Group"],
          },
          {
            Name: ["&No Group"],
          },
        ],
      },
    ],
    Tables: [
      {
        Table: [
          {
            Name: ["&Entry"],
            IsCustomized: ["true"],
          },
          {
            Name: ["&Entry"],
          },
        ],
      },
    ],
    Maps: [""],
    Reports: [""],
    Drawings: [""],
    DataLinks: [""],
    VBAProjects: [""],
    OutlineCodes: [""],
    WBSMasks: [""],
    ExtendedAttributes: [""],
    Calendars: [
      {
        Calendar: [
          {
            UID: ["1"],
            GUID: ["416FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            Name: ["Standard"],
            IsBaseCalendar: ["1"],
            IsBaselineCalendar: ["0"],
            BaseCalendarUID: ["-1"],
            WeekDays: [
              {
                WeekDay: [
                  {
                    DayType: ["1"],
                    DayWorking: ["0"],
                  },
                  {
                    DayType: ["2"],
                    DayWorking: ["1"],
                    WorkingTimes: [
                      {
                        WorkingTime: [
                          {
                            FromTime: ["08:00:00"],
                            ToTime: ["12:00:00"],
                          },
                          {
                            FromTime: ["13:00:00"],
                            ToTime: ["17:00:00"],
                          },
                        ],
                      },
                    ],
                  },
                  {
                    DayType: ["3"],
                    DayWorking: ["1"],
                    WorkingTimes: [
                      {
                        WorkingTime: [
                          {
                            FromTime: ["08:00:00"],
                            ToTime: ["12:00:00"],
                          },
                          {
                            FromTime: ["13:00:00"],
                            ToTime: ["17:00:00"],
                          },
                        ],
                      },
                    ],
                  },
                  {
                    DayType: ["4"],
                    DayWorking: ["1"],
                    WorkingTimes: [
                      {
                        WorkingTime: [
                          {
                            FromTime: ["08:00:00"],
                            ToTime: ["12:00:00"],
                          },
                          {
                            FromTime: ["13:00:00"],
                            ToTime: ["17:00:00"],
                          },
                        ],
                      },
                    ],
                  },
                  {
                    DayType: ["5"],
                    DayWorking: ["1"],
                    WorkingTimes: [
                      {
                        WorkingTime: [
                          {
                            FromTime: ["08:00:00"],
                            ToTime: ["12:00:00"],
                          },
                          {
                            FromTime: ["13:00:00"],
                            ToTime: ["17:00:00"],
                          },
                        ],
                      },
                    ],
                  },
                  {
                    DayType: ["6"],
                    DayWorking: ["1"],
                    WorkingTimes: [
                      {
                        WorkingTime: [
                          {
                            FromTime: ["08:00:00"],
                            ToTime: ["12:00:00"],
                          },
                          {
                            FromTime: ["13:00:00"],
                            ToTime: ["17:00:00"],
                          },
                        ],
                      },
                    ],
                  },
                  {
                    DayType: ["7"],
                    DayWorking: ["0"],
                  },
                ],
              },
            ],
          },
          {
            UID: ["3"],
            GUID: ["D5F20887-C754-EF11-B9EE-0892041FAD50"],
            Name: ["mech engineer 1"],
            IsBaseCalendar: ["0"],
            IsBaselineCalendar: ["0"],
            BaseCalendarUID: ["1"],
          },
          {
            UID: ["4"],
            GUID: ["900A9599-C754-EF11-B9EE-0892041FAD50"],
            Name: ["mech engineer 2"],
            IsBaseCalendar: ["0"],
            IsBaselineCalendar: ["0"],
            BaseCalendarUID: ["1"],
          },
          {
            UID: ["5"],
            GUID: ["87A335AA-C754-EF11-B9EE-0892041FAD50"],
            Name: ["elec engineer 1"],
            IsBaseCalendar: ["0"],
            IsBaselineCalendar: ["0"],
            BaseCalendarUID: ["1"],
          },
          {
            UID: ["6"],
            GUID: ["89A335AA-C754-EF11-B9EE-0892041FAD50"],
            Name: ["elec engineer 2"],
            IsBaseCalendar: ["0"],
            IsBaselineCalendar: ["0"],
            BaseCalendarUID: ["1"],
          },
          {
            UID: ["7"],
            GUID: ["B9477DCD-C754-EF11-B9EE-0892041FAD50"],
            Name: ["project manager"],
            IsBaseCalendar: ["0"],
            IsBaselineCalendar: ["0"],
            BaseCalendarUID: ["1"],
          },
        ],
      },
    ],
    Tasks: [
      {
        Task: [
          {
            UID: ["0"],
            GUID: ["336FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["0"],
            Name: ["Simple Project Plan"],
            Manual: ["0"],
            Type: ["1"],
            IsNull: ["0"],
            CreateDate: ["2024-08-07T15:12:00"],
            WBS: ["0"],
            OutlineNumber: ["0"],
            OutlineLevel: ["0"],
            Priority: ["500"],
            Start: ["2024-08-07T08:00:00"],
            Finish: ["2024-08-29T17:00:00"],
            Duration: ["PT136H0M0S"],
            ManualStart: ["2024-08-07T08:00:00"],
            ManualFinish: ["2024-08-29T17:00:00"],
            ManualDuration: ["PT136H0M0S"],
            DurationFormat: ["21"],
            FreeformDurationFormat: ["7"],
            Work: ["PT312H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["1"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-07T08:00:00"],
            EarlyFinish: ["2024-08-29T17:00:00"],
            LateStart: ["2024-08-07T08:00:00"],
            LateFinish: ["2024-08-29T17:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["18720000.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["1936000"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT312H0M0S"],
            RemainingDuration: ["PT136H0M0S"],
            RemainingCost: ["1936000"],
            RemainingWork: ["PT312H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            HideBar: ["0"],
            Rollup: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
          },
          {
            UID: ["2"],
            GUID: ["346FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["1"],
            Name: ["Summary #1"],
            Manual: ["0"],
            Type: ["1"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["1"],
            OutlineNumber: ["1"],
            OutlineLevel: ["1"],
            Priority: ["500"],
            Start: ["2024-08-07T08:00:00"],
            Finish: ["2024-08-13T17:00:00"],
            Duration: ["PT40H0M0S"],
            ManualStart: ["2024-08-07T08:00:00"],
            ManualFinish: ["2024-08-13T17:00:00"],
            ManualDuration: ["PT40H0M0S"],
            DurationFormat: ["21"],
            FreeformDurationFormat: ["21"],
            Work: ["PT104H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["1"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-07T08:00:00"],
            EarlyFinish: ["2024-08-13T17:00:00"],
            LateStart: ["2024-08-07T08:00:00"],
            LateFinish: ["2024-08-14T08:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["6240000.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["640000"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT104H0M0S"],
            RemainingDuration: ["PT40H0M0S"],
            RemainingCost: ["640000"],
            RemainingWork: ["PT104H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            Notes: [
              "This is a summary task. Use summary tasks to help organize your project into sections.",
            ],
            HideBar: ["0"],
            Rollup: ["1"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
          },
          {
            UID: ["3"],
            GUID: ["356FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["2"],
            Name: [" Task 1"],
            Manual: ["0"],
            Type: ["0"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["1.1"],
            OutlineNumber: ["1.1"],
            OutlineLevel: ["2"],
            Priority: ["500"],
            Start: ["2024-08-07T08:00:00"],
            Finish: ["2024-08-08T17:00:00"],
            Duration: ["PT16H0M0S"],
            ManualStart: ["2024-08-07T08:00:00"],
            ManualFinish: ["2024-08-08T17:00:00"],
            ManualDuration: ["PT16H0M0S"],
            DurationFormat: ["7"],
            FreeformDurationFormat: ["7"],
            Work: ["PT16H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["0"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-07T08:00:00"],
            EarlyFinish: ["2024-08-08T17:00:00"],
            LateStart: ["2024-08-07T08:00:00"],
            LateFinish: ["2024-08-08T17:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["960000.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["96000"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT16H0M0S"],
            RemainingDuration: ["PT16H0M0S"],
            RemainingCost: ["96000"],
            RemainingWork: ["PT16H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            HideBar: ["0"],
            Rollup: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
          },
          {
            UID: ["4"],
            GUID: ["366FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["3"],
            Name: [" Task 2"],
            Manual: ["0"],
            Type: ["0"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["1.2"],
            OutlineNumber: ["1.2"],
            OutlineLevel: ["2"],
            Priority: ["500"],
            Start: ["2024-08-09T08:00:00"],
            Finish: ["2024-08-13T17:00:00"],
            Duration: ["PT24H0M0S"],
            ManualStart: ["2024-08-09T08:00:00"],
            ManualFinish: ["2024-08-13T17:00:00"],
            ManualDuration: ["PT24H0M0S"],
            DurationFormat: ["7"],
            FreeformDurationFormat: ["7"],
            Work: ["PT48H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["0"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-09T08:00:00"],
            EarlyFinish: ["2024-08-13T17:00:00"],
            LateStart: ["2024-08-09T08:00:00"],
            LateFinish: ["2024-08-13T17:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["2880000.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["264000"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT48H0M0S"],
            RemainingDuration: ["PT24H0M0S"],
            RemainingCost: ["264000"],
            RemainingWork: ["PT48H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            HideBar: ["0"],
            Rollup: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
            PredecessorLink: [
              {
                PredecessorUID: ["3"],
                Type: ["1"],
                CrossProject: ["0"],
                LinkLag: ["0"],
                LagFormat: ["7"],
              },
            ],
          },
          {
            UID: ["6"],
            GUID: ["376FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["4"],
            Name: ["Summary #1 Complete"],
            Manual: ["0"],
            Type: ["0"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["1.3"],
            OutlineNumber: ["1.3"],
            OutlineLevel: ["2"],
            Priority: ["500"],
            Start: ["2024-08-13T17:00:00"],
            Finish: ["2024-08-13T17:00:00"],
            Duration: ["PT0H0M0S"],
            ManualStart: ["2024-08-13T17:00:00"],
            ManualFinish: ["2024-08-13T17:00:00"],
            ManualDuration: ["PT0H0M0S"],
            DurationFormat: ["7"],
            FreeformDurationFormat: ["7"],
            Work: ["PT0H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["1"],
            Summary: ["0"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-13T17:00:00"],
            EarlyFinish: ["2024-08-13T17:00:00"],
            LateStart: ["2024-08-14T08:00:00"],
            LateFinish: ["2024-08-14T08:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["0.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT0H0M0S"],
            RemainingDuration: ["PT0H0M0S"],
            RemainingCost: ["0"],
            RemainingWork: ["PT0H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            Notes: [
              "This is a milestone task. Set a task to 0d duration to mark an event in your project.",
            ],
            HideBar: ["0"],
            Rollup: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
            PredecessorLink: [
              {
                PredecessorUID: ["4"],
                Type: ["1"],
                CrossProject: ["0"],
                LinkLag: ["0"],
                LagFormat: ["7"],
              },
            ],
          },
          {
            UID: ["7"],
            GUID: ["386FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["5"],
            Name: ["Summary #2"],
            Manual: ["0"],
            Type: ["1"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["2"],
            OutlineNumber: ["2"],
            OutlineLevel: ["1"],
            Priority: ["500"],
            Start: ["2024-08-14T08:00:00"],
            Finish: ["2024-08-26T17:00:00"],
            Duration: ["PT72H0M0S"],
            ManualStart: ["2024-08-14T08:00:00"],
            ManualFinish: ["2024-08-26T17:00:00"],
            ManualDuration: ["PT72H0M0S"],
            DurationFormat: ["21"],
            FreeformDurationFormat: ["21"],
            Work: ["PT160H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["1"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-14T08:00:00"],
            EarlyFinish: ["2024-08-26T17:00:00"],
            LateStart: ["2024-08-14T08:00:00"],
            LateFinish: ["2024-08-27T08:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["9600000.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["1008000"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT160H0M0S"],
            RemainingDuration: ["PT72H0M0S"],
            RemainingCost: ["1008000"],
            RemainingWork: ["PT160H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            HideBar: ["0"],
            Rollup: ["1"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
          },
          {
            UID: ["8"],
            GUID: ["396FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["6"],
            Name: [" Task 3"],
            Manual: ["0"],
            Type: ["0"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["2.1"],
            OutlineNumber: ["2.1"],
            OutlineLevel: ["2"],
            Priority: ["500"],
            Start: ["2024-08-14T08:00:00"],
            Finish: ["2024-08-16T17:00:00"],
            Duration: ["PT24H0M0S"],
            ManualStart: ["2024-08-14T08:00:00"],
            ManualFinish: ["2024-08-16T17:00:00"],
            ManualDuration: ["PT24H0M0S"],
            DurationFormat: ["7"],
            FreeformDurationFormat: ["21"],
            Work: ["PT24H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["0"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-14T08:00:00"],
            EarlyFinish: ["2024-08-16T17:00:00"],
            LateStart: ["2024-08-14T08:00:00"],
            LateFinish: ["2024-08-16T17:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["1440000.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["120000"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT24H0M0S"],
            RemainingDuration: ["PT24H0M0S"],
            RemainingCost: ["120000"],
            RemainingWork: ["PT24H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["6"],
            CalendarUID: ["-1"],
            ConstraintDate: ["2024-08-12T17:00:00"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            HideBar: ["0"],
            Rollup: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
            PredecessorLink: [
              {
                PredecessorUID: ["6"],
                Type: ["1"],
                CrossProject: ["0"],
                LinkLag: ["0"],
                LagFormat: ["7"],
              },
            ],
          },
          {
            UID: ["9"],
            GUID: ["3A6FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["7"],
            Name: [" Task 4"],
            Manual: ["0"],
            Type: ["0"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["2.2"],
            OutlineNumber: ["2.2"],
            OutlineLevel: ["2"],
            Priority: ["500"],
            Start: ["2024-08-19T08:00:00"],
            Finish: ["2024-08-22T17:00:00"],
            Duration: ["PT32H0M0S"],
            ManualStart: ["2024-08-19T08:00:00"],
            ManualFinish: ["2024-08-22T17:00:00"],
            ManualDuration: ["PT32H0M0S"],
            DurationFormat: ["7"],
            FreeformDurationFormat: ["21"],
            Work: ["PT32H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["0"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-19T08:00:00"],
            EarlyFinish: ["2024-08-22T17:00:00"],
            LateStart: ["2024-08-19T08:00:00"],
            LateFinish: ["2024-08-22T17:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["1920000.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["192000"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT32H0M0S"],
            RemainingDuration: ["PT32H0M0S"],
            RemainingCost: ["192000"],
            RemainingWork: ["PT32H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            HideBar: ["0"],
            Rollup: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
            PredecessorLink: [
              {
                PredecessorUID: ["8"],
                Type: ["1"],
                CrossProject: ["0"],
                LinkLag: ["0"],
                LagFormat: ["7"],
              },
            ],
          },
          {
            UID: ["10"],
            GUID: ["3B6FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["8"],
            Name: ["Task 5"],
            Manual: ["0"],
            Type: ["0"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["2.3"],
            OutlineNumber: ["2.3"],
            OutlineLevel: ["2"],
            Priority: ["500"],
            Start: ["2024-08-23T08:00:00"],
            Finish: ["2024-08-26T17:00:00"],
            Duration: ["PT16H0M0S"],
            ManualStart: ["2024-08-23T08:00:00"],
            ManualFinish: ["2024-08-26T17:00:00"],
            ManualDuration: ["PT16H0M0S"],
            DurationFormat: ["7"],
            FreeformDurationFormat: ["21"],
            Work: ["PT32H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["0"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-23T08:00:00"],
            EarlyFinish: ["2024-08-26T17:00:00"],
            LateStart: ["2024-08-23T08:00:00"],
            LateFinish: ["2024-08-26T17:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["1920000.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["192000"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT32H0M0S"],
            RemainingDuration: ["PT16H0M0S"],
            RemainingCost: ["192000"],
            RemainingWork: ["PT32H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            HideBar: ["0"],
            Rollup: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
            PredecessorLink: [
              {
                PredecessorUID: ["9"],
                Type: ["1"],
                CrossProject: ["0"],
                LinkLag: ["0"],
                LagFormat: ["7"],
              },
            ],
          },
          {
            UID: ["12"],
            GUID: ["3C6FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["9"],
            Name: ["Summary #2 Complete"],
            Manual: ["0"],
            Type: ["0"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["2.4"],
            OutlineNumber: ["2.4"],
            OutlineLevel: ["2"],
            Priority: ["500"],
            Start: ["2024-08-26T17:00:00"],
            Finish: ["2024-08-26T17:00:00"],
            Duration: ["PT0H0M0S"],
            ManualStart: ["2024-08-26T17:00:00"],
            ManualFinish: ["2024-08-26T17:00:00"],
            ManualDuration: ["PT0H0M0S"],
            DurationFormat: ["7"],
            FreeformDurationFormat: ["7"],
            Work: ["PT0H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["1"],
            Summary: ["0"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-26T17:00:00"],
            EarlyFinish: ["2024-08-26T17:00:00"],
            LateStart: ["2024-08-27T08:00:00"],
            LateFinish: ["2024-08-27T08:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["0.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT0H0M0S"],
            RemainingDuration: ["PT0H0M0S"],
            RemainingCost: ["0"],
            RemainingWork: ["PT0H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            HideBar: ["0"],
            Rollup: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
            PredecessorLink: [
              {
                PredecessorUID: ["10"],
                Type: ["1"],
                CrossProject: ["0"],
                LinkLag: ["0"],
                LagFormat: ["7"],
              },
            ],
          },
          {
            UID: ["13"],
            GUID: ["3D6FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["10"],
            Name: ["Summary #3"],
            Manual: ["0"],
            Type: ["1"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["3"],
            OutlineNumber: ["3"],
            OutlineLevel: ["1"],
            Priority: ["500"],
            Start: ["2024-08-27T08:00:00"],
            Finish: ["2024-08-29T17:00:00"],
            Duration: ["PT24H0M0S"],
            ManualStart: ["2024-08-27T08:00:00"],
            ManualFinish: ["2024-08-29T17:00:00"],
            ManualDuration: ["PT24H0M0S"],
            DurationFormat: ["21"],
            FreeformDurationFormat: ["21"],
            Work: ["PT48H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["1"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-27T08:00:00"],
            EarlyFinish: ["2024-08-29T17:00:00"],
            LateStart: ["2024-08-27T08:00:00"],
            LateFinish: ["2024-08-29T17:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["2880000.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["288000"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT48H0M0S"],
            RemainingDuration: ["PT24H0M0S"],
            RemainingCost: ["288000"],
            RemainingWork: ["PT48H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            HideBar: ["0"],
            Rollup: ["1"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
          },
          {
            UID: ["14"],
            GUID: ["3E6FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["11"],
            Name: ["Task 6"],
            Manual: ["1"],
            Type: ["0"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["3.1"],
            OutlineNumber: ["3.1"],
            OutlineLevel: ["2"],
            Priority: ["500"],
            Start: ["2024-08-27T08:00:00"],
            Finish: ["2024-08-29T17:00:00"],
            Duration: ["PT24H0M0S"],
            ManualStart: ["2024-08-27T08:00:00"],
            ManualFinish: ["2024-08-29T17:00:00"],
            ManualDuration: ["PT24H0M0S"],
            DurationFormat: ["7"],
            FreeformDurationFormat: ["7"],
            Work: ["PT24H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["0"],
            DisplayAsSummary: ["0"],
            Critical: ["1"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-27T08:00:00"],
            EarlyFinish: ["2024-08-29T17:00:00"],
            LateStart: ["2024-08-27T08:00:00"],
            LateFinish: ["2024-08-29T17:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["1440000.00"],
            FreeSlack: ["0"],
            TotalSlack: ["0"],
            StartSlack: ["0"],
            FinishSlack: ["0"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["120000"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT24H0M0S"],
            RemainingDuration: ["PT24H0M0S"],
            RemainingCost: ["120000"],
            RemainingWork: ["PT24H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            Notes: [
              "Tasks with the pushpin next to them are manually scheduled tasks. Use them when you don't want Project to move the task. Also, you can enter freeform text in the duration, start and finish fields or leave them blank if you don't have all the information yet.",
            ],
            HideBar: ["0"],
            Rollup: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
            PredecessorLink: [
              {
                PredecessorUID: ["12"],
                Type: ["1"],
                CrossProject: ["0"],
                LinkLag: ["0"],
                LagFormat: ["7"],
              },
            ],
          },
          {
            UID: ["15"],
            GUID: ["3F6FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["12"],
            Name: ["Task 7"],
            Manual: ["1"],
            Type: ["0"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["3.2"],
            OutlineNumber: ["3.2"],
            OutlineLevel: ["2"],
            Priority: ["500"],
            StartText: [""],
            FinishText: [""],
            Start: ["2024-08-27T08:00:00"],
            Finish: ["2024-08-28T17:00:00"],
            Duration: ["PT16H0M0S"],
            ManualStart: ["2024-08-27T08:00:00"],
            ManualFinish: ["2024-08-28T17:00:00"],
            ManualDuration: ["PT16H0M0S"],
            DurationFormat: ["7"],
            FreeformDurationFormat: ["7"],
            Work: ["PT0H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["0"],
            DisplayAsSummary: ["0"],
            Critical: ["0"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-27T08:00:00"],
            EarlyFinish: ["2024-08-28T17:00:00"],
            LateStart: ["2024-08-28T08:00:00"],
            LateFinish: ["2024-08-29T17:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["0.00"],
            FreeSlack: ["4800"],
            TotalSlack: ["4800"],
            StartSlack: ["4800"],
            FinishSlack: ["4800"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT0H0M0S"],
            RemainingDuration: ["PT16H0M0S"],
            RemainingCost: ["0"],
            RemainingWork: ["PT0H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            HideBar: ["0"],
            Rollup: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
          },
          {
            UID: ["16"],
            GUID: ["406FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            ID: ["13"],
            Name: ["Task 8"],
            Manual: ["1"],
            Type: ["0"],
            IsNull: ["0"],
            CreateDate: ["2012-08-09T17:46:00"],
            WBS: ["3.3"],
            OutlineNumber: ["3.3"],
            OutlineLevel: ["2"],
            Priority: ["500"],
            StartText: [""],
            FinishText: [""],
            DurationText: ["TBD"],
            Start: ["2024-08-27T08:00:00"],
            Finish: ["2024-08-27T17:00:00"],
            Duration: ["PT8H0M0S"],
            ManualStart: ["2024-08-27T08:00:00"],
            ManualFinish: ["2024-08-27T17:00:00"],
            ManualDuration: ["PT8H0M0S"],
            DurationFormat: ["21"],
            FreeformDurationFormat: ["21"],
            Work: ["PT0H0M0S"],
            ResumeValid: ["0"],
            EffortDriven: ["0"],
            Recurring: ["0"],
            OverAllocated: ["0"],
            Estimated: ["0"],
            Milestone: ["0"],
            Summary: ["0"],
            DisplayAsSummary: ["0"],
            Critical: ["0"],
            IsSubproject: ["0"],
            IsSubprojectReadOnly: ["0"],
            ExternalTask: ["0"],
            EarlyStart: ["2024-08-27T08:00:00"],
            EarlyFinish: ["2024-08-27T17:00:00"],
            LateStart: ["2024-08-29T08:00:00"],
            LateFinish: ["2024-08-29T17:00:00"],
            StartVariance: ["0"],
            FinishVariance: ["0"],
            WorkVariance: ["0.00"],
            FreeSlack: ["9600"],
            TotalSlack: ["9600"],
            StartSlack: ["9600"],
            FinishSlack: ["9600"],
            FixedCost: ["0"],
            FixedCostAccrual: ["3"],
            PercentComplete: ["0"],
            PercentWorkComplete: ["0"],
            Cost: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            ActualDuration: ["PT0H0M0S"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT0H0M0S"],
            RemainingDuration: ["PT8H0M0S"],
            RemainingCost: ["0"],
            RemainingWork: ["PT0H0M0S"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            CV: ["0.00"],
            ConstraintType: ["0"],
            CalendarUID: ["-1"],
            LevelAssignments: ["1"],
            LevelingCanSplit: ["1"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["8"],
            IgnoreResourceCalendar: ["0"],
            HideBar: ["0"],
            Rollup: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            PhysicalPercentComplete: ["0"],
            EarnedValueMethod: ["0"],
          },
        ],
      },
    ],
    Resources: [
      {
        Resource: [
          {
            UID: ["0"],
            GUID: ["A0CB8B7E-2A8C-436D-0000-0000000000FF"],
            ID: ["0"],
            Type: ["1"],
            IsNull: ["0"],
            MaxUnits: ["1.00"],
            PeakUnits: ["0.00"],
            OverAllocated: ["0"],
            CanLevel: ["1"],
            AccrueAt: ["3"],
            Work: ["PT0H0M0S"],
            RegularWork: ["PT0H0M0S"],
            OvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            RemainingWork: ["PT0H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            PercentWorkComplete: ["0"],
            StandardRate: ["0"],
            StandardRateFormat: ["2"],
            Cost: ["0"],
            OvertimeRate: ["0"],
            OvertimeRateFormat: ["2"],
            OvertimeCost: ["0"],
            CostPerUse: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            RemainingCost: ["0"],
            RemainingOvertimeCost: ["0"],
            WorkVariance: ["0.00"],
            CostVariance: ["0"],
            SV: ["0.00"],
            CV: ["0.00"],
            ACWP: ["0.00"],
            CalendarUID: ["2"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2012-08-09T17:46:00"],
            IsCostResource: ["0"],
            IsBudget: ["0"],
          },
          {
            UID: ["1"],
            GUID: ["D5F20887-C754-EF11-B9EE-0892041FAD50"],
            ID: ["1"],
            Name: ["mech engineer 1"],
            Type: ["1"],
            IsNull: ["0"],
            Initials: ["W"],
            EmailAddress: ["willy@mail.com"],
            MaxUnits: ["1.00"],
            PeakUnits: ["1.00"],
            OverAllocated: ["0"],
            CanLevel: ["1"],
            AccrueAt: ["3"],
            Work: ["PT24H0M0S"],
            RegularWork: ["PT24H0M0S"],
            OvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            RemainingWork: ["PT24H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            PercentWorkComplete: ["0"],
            StandardRate: ["50"],
            StandardRateFormat: ["2"],
            Cost: ["120000"],
            OvertimeRate: ["0"],
            OvertimeRateFormat: ["2"],
            OvertimeCost: ["0"],
            CostPerUse: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            RemainingCost: ["120000"],
            RemainingOvertimeCost: ["0"],
            WorkVariance: ["1440000.00"],
            CostVariance: ["120000"],
            SV: ["0.00"],
            CV: ["0.00"],
            ACWP: ["0.00"],
            CalendarUID: ["3"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:15:00"],
            IsCostResource: ["0"],
            IsBudget: ["0"],
          },
          {
            UID: ["2"],
            GUID: ["900A9599-C754-EF11-B9EE-0892041FAD50"],
            ID: ["2"],
            Name: ["mech engineer 2"],
            Type: ["1"],
            IsNull: ["0"],
            Initials: ["L"],
            EmailAddress: ["luigi@mail.com"],
            MaxUnits: ["1.00"],
            PeakUnits: ["1.00"],
            OverAllocated: ["0"],
            CanLevel: ["1"],
            AccrueAt: ["3"],
            Work: ["PT48H0M0S"],
            RegularWork: ["PT48H0M0S"],
            OvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            RemainingWork: ["PT48H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            PercentWorkComplete: ["0"],
            StandardRate: ["50"],
            StandardRateFormat: ["2"],
            Cost: ["240000"],
            OvertimeRate: ["0"],
            OvertimeRateFormat: ["2"],
            OvertimeCost: ["0"],
            CostPerUse: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            RemainingCost: ["240000"],
            RemainingOvertimeCost: ["0"],
            WorkVariance: ["2880000.00"],
            CostVariance: ["240000"],
            SV: ["0.00"],
            CV: ["0.00"],
            ACWP: ["0.00"],
            CalendarUID: ["4"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:16:00"],
            IsCostResource: ["0"],
            IsBudget: ["0"],
          },
          {
            UID: ["3"],
            GUID: ["87A335AA-C754-EF11-B9EE-0892041FAD50"],
            ID: ["3"],
            Name: ["elec engineer 1"],
            Type: ["1"],
            IsNull: ["0"],
            Initials: ["P"],
            EmailAddress: ["pamela@mail.com"],
            MaxUnits: ["1.00"],
            PeakUnits: ["1.00"],
            OverAllocated: ["0"],
            CanLevel: ["1"],
            AccrueAt: ["3"],
            Work: ["PT32H0M0S"],
            RegularWork: ["PT32H0M0S"],
            OvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            RemainingWork: ["PT32H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            PercentWorkComplete: ["0"],
            StandardRate: ["60"],
            StandardRateFormat: ["2"],
            Cost: ["192000"],
            OvertimeRate: ["0"],
            OvertimeRateFormat: ["2"],
            OvertimeCost: ["0"],
            CostPerUse: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            RemainingCost: ["192000"],
            RemainingOvertimeCost: ["0"],
            WorkVariance: ["1920000.00"],
            CostVariance: ["192000"],
            SV: ["0.00"],
            CV: ["0.00"],
            ACWP: ["0.00"],
            CalendarUID: ["5"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:16:00"],
            IsCostResource: ["0"],
            IsBudget: ["0"],
          },
          {
            UID: ["4"],
            GUID: ["89A335AA-C754-EF11-B9EE-0892041FAD50"],
            ID: ["4"],
            Name: ["elec engineer 2"],
            Type: ["1"],
            IsNull: ["0"],
            Initials: ["H"],
            EmailAddress: ["hogan@mail.com"],
            MaxUnits: ["1.00"],
            PeakUnits: ["1.00"],
            OverAllocated: ["0"],
            CanLevel: ["1"],
            AccrueAt: ["3"],
            Work: ["PT72H0M0S"],
            RegularWork: ["PT72H0M0S"],
            OvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            RemainingWork: ["PT72H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            PercentWorkComplete: ["0"],
            StandardRate: ["60"],
            StandardRateFormat: ["2"],
            Cost: ["432000"],
            OvertimeRate: ["0"],
            OvertimeRateFormat: ["2"],
            OvertimeCost: ["0"],
            CostPerUse: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            RemainingCost: ["432000"],
            RemainingOvertimeCost: ["0"],
            WorkVariance: ["4320000.00"],
            CostVariance: ["432000"],
            SV: ["0.00"],
            CV: ["0.00"],
            ACWP: ["0.00"],
            CalendarUID: ["6"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:16:00"],
            IsCostResource: ["0"],
            IsBudget: ["0"],
          },
          {
            UID: ["5"],
            GUID: ["B9477DCD-C754-EF11-B9EE-0892041FAD50"],
            ID: ["5"],
            Name: ["project manager"],
            Type: ["1"],
            IsNull: ["0"],
            Initials: ["M"],
            EmailAddress: ["mario@mail.com"],
            MaxUnits: ["1.00"],
            PeakUnits: ["1.00"],
            OverAllocated: ["0"],
            CanLevel: ["1"],
            AccrueAt: ["3"],
            Work: ["PT136H0M0S"],
            RegularWork: ["PT136H0M0S"],
            OvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            RemainingWork: ["PT136H0M0S"],
            ActualOvertimeWork: ["PT0H0M0S"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            PercentWorkComplete: ["0"],
            StandardRate: ["70"],
            StandardRateFormat: ["2"],
            Cost: ["952000"],
            OvertimeRate: ["0"],
            OvertimeRateFormat: ["2"],
            OvertimeCost: ["0"],
            CostPerUse: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            RemainingCost: ["952000"],
            RemainingOvertimeCost: ["0"],
            WorkVariance: ["8160000.00"],
            CostVariance: ["952000"],
            SV: ["0.00"],
            CV: ["0.00"],
            ACWP: ["0.00"],
            CalendarUID: ["7"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:17:00"],
            IsCostResource: ["0"],
            IsBudget: ["0"],
          },
        ],
      },
    ],
    Assignments: [
      {
        Assignment: [
          {
            UID: ["3"],
            GUID: ["436FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            TaskUID: ["3"],
            ResourceUID: ["3"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["96000"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["96000"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-08T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["960000.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT16H0M0S"],
            RemainingCost: ["96000"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT16H0M0S"],
            Start: ["2024-08-07T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT16H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:19:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["3"],
                Start: ["2024-08-07T08:00:00"],
                Finish: ["2024-08-08T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["3"],
                Start: ["2024-08-08T08:00:00"],
                Finish: ["2024-08-08T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["4"],
            GUID: ["446FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            TaskUID: ["4"],
            ResourceUID: ["4"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["144000"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["144000"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-13T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["1440000.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT24H0M0S"],
            RemainingCost: ["144000"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT24H0M0S"],
            Start: ["2024-08-09T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT24H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:19:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["4"],
                Start: ["2024-08-09T08:00:00"],
                Finish: ["2024-08-10T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["4"],
                Start: ["2024-08-10T08:00:00"],
                Finish: ["2024-08-12T08:00:00"],
                Unit: ["1"],
                Value: ["PT0H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["4"],
                Start: ["2024-08-12T08:00:00"],
                Finish: ["2024-08-13T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["4"],
                Start: ["2024-08-13T08:00:00"],
                Finish: ["2024-08-13T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["6"],
            GUID: ["456FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            TaskUID: ["6"],
            ResourceUID: ["5"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["0"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["0"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-13T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["0.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["1"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT0H0M0S"],
            RemainingCost: ["0"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT0H0M0S"],
            Start: ["2024-08-13T17:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT0H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:19:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
          },
          {
            UID: ["8"],
            GUID: ["466FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            TaskUID: ["8"],
            ResourceUID: ["2"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["120000"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["120000"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-16T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["1440000.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT24H0M0S"],
            RemainingCost: ["120000"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT24H0M0S"],
            Start: ["2024-08-14T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT24H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:19:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["8"],
                Start: ["2024-08-14T08:00:00"],
                Finish: ["2024-08-15T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["8"],
                Start: ["2024-08-15T08:00:00"],
                Finish: ["2024-08-16T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["8"],
                Start: ["2024-08-16T08:00:00"],
                Finish: ["2024-08-16T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["9"],
            GUID: ["476FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            TaskUID: ["9"],
            ResourceUID: ["4"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["192000"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["192000"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-22T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["1920000.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT32H0M0S"],
            RemainingCost: ["192000"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT32H0M0S"],
            Start: ["2024-08-19T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT32H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:20:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["9"],
                Start: ["2024-08-19T08:00:00"],
                Finish: ["2024-08-20T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["9"],
                Start: ["2024-08-20T08:00:00"],
                Finish: ["2024-08-21T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["9"],
                Start: ["2024-08-21T08:00:00"],
                Finish: ["2024-08-22T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["9"],
                Start: ["2024-08-22T08:00:00"],
                Finish: ["2024-08-22T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["10"],
            GUID: ["486FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            TaskUID: ["10"],
            ResourceUID: ["3"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["96000"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["96000"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-26T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["960000.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT16H0M0S"],
            RemainingCost: ["96000"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT16H0M0S"],
            Start: ["2024-08-23T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT16H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:20:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["10"],
                Start: ["2024-08-23T08:00:00"],
                Finish: ["2024-08-24T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["10"],
                Start: ["2024-08-24T08:00:00"],
                Finish: ["2024-08-26T08:00:00"],
                Unit: ["1"],
                Value: ["PT0H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["10"],
                Start: ["2024-08-26T08:00:00"],
                Finish: ["2024-08-26T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["12"],
            GUID: ["496FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            TaskUID: ["12"],
            ResourceUID: ["5"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["0"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["0"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-26T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["0.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["1"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT0H0M0S"],
            RemainingCost: ["0"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT0H0M0S"],
            Start: ["2024-08-26T17:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT0H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:20:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
          },
          {
            UID: ["14"],
            GUID: ["4A6FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            TaskUID: ["14"],
            ResourceUID: ["1"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["120000"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["120000"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-29T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["1440000.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT24H0M0S"],
            RemainingCost: ["120000"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT24H0M0S"],
            Start: ["2024-08-27T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT24H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:20:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["14"],
                Start: ["2024-08-27T08:00:00"],
                Finish: ["2024-08-28T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["14"],
                Start: ["2024-08-28T08:00:00"],
                Finish: ["2024-08-29T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["14"],
                Start: ["2024-08-29T08:00:00"],
                Finish: ["2024-08-29T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["15"],
            GUID: ["4B6FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            TaskUID: ["15"],
            ResourceUID: ["-65535"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["0"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["0"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-28T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["0.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT16H0M0S"],
            RemainingCost: ["0"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT16H0M0S"],
            Start: ["2024-08-27T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT16H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2012-08-09T17:46:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["15"],
                Start: ["2024-08-27T08:00:00"],
                Finish: ["2024-08-28T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["15"],
                Start: ["2024-08-28T08:00:00"],
                Finish: ["2024-08-28T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["16"],
            GUID: ["4C6FBF06-40E8-E111-ACCD-F0DEF1A69BD1"],
            TaskUID: ["16"],
            ResourceUID: ["-65535"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["0"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["0"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-27T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["0.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT8H0M0S"],
            RemainingCost: ["0"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT8H0M0S"],
            Start: ["2024-08-27T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT8H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2012-08-09T17:46:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["16"],
                Start: ["2024-08-27T08:00:00"],
                Finish: ["2024-08-27T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["17"],
            GUID: ["2F48FCD9-C754-EF11-B9EE-0892041FAD50"],
            TaskUID: ["2"],
            ResourceUID: ["5"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["280000"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["280000"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-13T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["2400000.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT40H0M0S"],
            RemainingCost: ["280000"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT40H0M0S"],
            Start: ["2024-08-07T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT40H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:18:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["17"],
                Start: ["2024-08-07T08:00:00"],
                Finish: ["2024-08-08T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["17"],
                Start: ["2024-08-08T08:00:00"],
                Finish: ["2024-08-09T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["17"],
                Start: ["2024-08-09T08:00:00"],
                Finish: ["2024-08-10T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["17"],
                Start: ["2024-08-10T08:00:00"],
                Finish: ["2024-08-12T08:00:00"],
                Unit: ["1"],
                Value: ["PT0H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["17"],
                Start: ["2024-08-12T08:00:00"],
                Finish: ["2024-08-13T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["17"],
                Start: ["2024-08-13T08:00:00"],
                Finish: ["2024-08-13T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["18"],
            GUID: ["E69BBF05-C854-EF11-B9EE-0892041FAD50"],
            TaskUID: ["7"],
            ResourceUID: ["5"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["504000"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["504000"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-26T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["4320000.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT72H0M0S"],
            RemainingCost: ["504000"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT72H0M0S"],
            Start: ["2024-08-14T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT72H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:19:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["18"],
                Start: ["2024-08-14T08:00:00"],
                Finish: ["2024-08-15T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["18"],
                Start: ["2024-08-15T08:00:00"],
                Finish: ["2024-08-16T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["18"],
                Start: ["2024-08-16T08:00:00"],
                Finish: ["2024-08-17T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["18"],
                Start: ["2024-08-17T08:00:00"],
                Finish: ["2024-08-19T08:00:00"],
                Unit: ["1"],
                Value: ["PT0H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["18"],
                Start: ["2024-08-19T08:00:00"],
                Finish: ["2024-08-20T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["18"],
                Start: ["2024-08-20T08:00:00"],
                Finish: ["2024-08-21T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["18"],
                Start: ["2024-08-21T08:00:00"],
                Finish: ["2024-08-22T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["18"],
                Start: ["2024-08-22T08:00:00"],
                Finish: ["2024-08-23T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["18"],
                Start: ["2024-08-23T08:00:00"],
                Finish: ["2024-08-24T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["18"],
                Start: ["2024-08-24T08:00:00"],
                Finish: ["2024-08-26T08:00:00"],
                Unit: ["1"],
                Value: ["PT0H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["18"],
                Start: ["2024-08-26T08:00:00"],
                Finish: ["2024-08-26T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["19"],
            GUID: ["E79BBF05-C854-EF11-B9EE-0892041FAD50"],
            TaskUID: ["13"],
            ResourceUID: ["5"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["168000"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["168000"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-29T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["1440000.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT24H0M0S"],
            RemainingCost: ["168000"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT24H0M0S"],
            Start: ["2024-08-27T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT24H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:19:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["19"],
                Start: ["2024-08-27T08:00:00"],
                Finish: ["2024-08-28T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["19"],
                Start: ["2024-08-28T08:00:00"],
                Finish: ["2024-08-29T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["19"],
                Start: ["2024-08-29T08:00:00"],
                Finish: ["2024-08-29T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["20"],
            GUID: ["7ACC6911-C854-EF11-B9EE-0892041FAD50"],
            TaskUID: ["4"],
            ResourceUID: ["2"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["120000"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["120000"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-13T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["1440000.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT24H0M0S"],
            RemainingCost: ["120000"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT24H0M0S"],
            Start: ["2024-08-09T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT24H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:19:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["20"],
                Start: ["2024-08-09T08:00:00"],
                Finish: ["2024-08-10T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["20"],
                Start: ["2024-08-10T08:00:00"],
                Finish: ["2024-08-12T08:00:00"],
                Unit: ["1"],
                Value: ["PT0H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["20"],
                Start: ["2024-08-12T08:00:00"],
                Finish: ["2024-08-13T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["20"],
                Start: ["2024-08-13T08:00:00"],
                Finish: ["2024-08-13T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
          {
            UID: ["21"],
            GUID: ["F8A00926-C854-EF11-B9EE-0892041FAD50"],
            TaskUID: ["10"],
            ResourceUID: ["4"],
            PercentWorkComplete: ["0"],
            ActualCost: ["0"],
            ActualOvertimeCost: ["0"],
            ActualOvertimeWork: ["PT0H0M0S"],
            ActualWork: ["PT0H0M0S"],
            ACWP: ["0.00"],
            Cost: ["96000"],
            CostRateTable: ["0"],
            RateScale: ["0"],
            CostVariance: ["96000"],
            CV: ["0.00"],
            Delay: ["0"],
            Finish: ["2024-08-26T17:00:00"],
            FinishVariance: ["0"],
            WorkVariance: ["960000.00"],
            HasFixedRateUnits: ["1"],
            FixedMaterial: ["0"],
            LevelingDelay: ["0"],
            LevelingDelayFormat: ["7"],
            LinkedFields: ["0"],
            Milestone: ["0"],
            Overallocated: ["0"],
            OvertimeCost: ["0"],
            OvertimeWork: ["PT0H0M0S"],
            RegularWork: ["PT16H0M0S"],
            RemainingCost: ["96000"],
            RemainingOvertimeCost: ["0"],
            RemainingOvertimeWork: ["PT0H0M0S"],
            RemainingWork: ["PT16H0M0S"],
            Start: ["2024-08-23T08:00:00"],
            StartVariance: ["0"],
            Units: ["1"],
            VAC: ["0.00"],
            Work: ["PT16H0M0S"],
            WorkContour: ["0"],
            BCWS: ["0.00"],
            BCWP: ["0.00"],
            CreationDate: ["2024-08-07T15:20:00"],
            BudgetCost: ["0"],
            BudgetWork: ["PT0H0M0S"],
            TimephasedData: [
              {
                Type: ["1"],
                UID: ["21"],
                Start: ["2024-08-23T08:00:00"],
                Finish: ["2024-08-24T08:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["21"],
                Start: ["2024-08-24T08:00:00"],
                Finish: ["2024-08-26T08:00:00"],
                Unit: ["1"],
                Value: ["PT0H0M0S"],
              },
              {
                Type: ["1"],
                UID: ["21"],
                Start: ["2024-08-26T08:00:00"],
                Finish: ["2024-08-26T17:00:00"],
                Unit: ["1"],
                Value: ["PT8H0M0S"],
              },
            ],
          },
        ],
      },
    ],
  },
};

const reqFile = {
  fieldname: "file",
  originalname: "startup business plan (5).xml",
  encoding: "7bit",
  mimetype: "text/xml",
  destination: "../../public/data/uploads/",
  filename: "3c7f9b2b7028ba85c7f9bfcf3566fe6e",
  path: "../../public/data/uploads/3c7f9b2b7028ba85c7f9bfcf3566fe6e",
  size: 575304,
};
