name: Playwright Tests

on:
  push:
    # paths:
    #   - "Projects_EndToEndTests/**"
    # branches: [main, master]
  pull_request:
    # paths:
    #   - "Projects_EndToEndTests/**"
    # branches: [main, master]

env:
  BASE_API_URL: https://projects-app-90ge.onrender.com
  BASE_FRONTEND_URL: https://projects-app-front-end.onrender.com/
  PW: Password123!

defaults:
  run:
    working-directory: ./Projects_EndToEndTests

permissions:
  pull-requests: write

jobs:
  workflow-telemetry-action:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # env:
    #   BASE_API_URL: ${{ vars.BASE_API_URL }}
    #   BASE_FRONTEND_URL: ${{ vars.BASE_FRONTEND_URL }}
    #   PW: ${{ vars.PW }}
    steps:
      - uses: actions/checkout@v4
        # env:
        #   BASE_API_URL: ${{ vars.BASE_API_URL }}
        #   BASE_FRONTEND_URL: ${{ vars.BASE_FRONTEND_URL }}
        #   PW: ${{ vars.PW }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      - name: Run Playwright tests
        run: npx playwright test --project=e2e-test --reporter=html
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/*
          retention-days: 30
